"""add_drug_authenticity_checks_table

Revision ID: 053168080fc3
Revises: b57dea08c230
Create Date: 2025-11-06 19:36:17.107699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '053168080fc3'
down_revision = 'b57dea08c230'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_authenticity_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('drug_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('drug_name_normalized', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('search_query', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('authenticity_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('detailed_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('search_timestamp', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_authenticity_checks_authenticity_status'), 'drug_authenticity_checks', ['authenticity_status'], unique=False)
    op.create_index(op.f('ix_drug_authenticity_checks_drug_name'), 'drug_authenticity_checks', ['drug_name'], unique=False)
    op.create_index(op.f('ix_drug_authenticity_checks_drug_name_normalized'), 'drug_authenticity_checks', ['drug_name_normalized'], unique=False)
    op.create_index(op.f('ix_drug_authenticity_checks_expires_at'), 'drug_authenticity_checks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_drug_authenticity_checks_search_timestamp'), 'drug_authenticity_checks', ['search_timestamp'], unique=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_drug_authenticity_checks_search_timestamp'), table_name='drug_authenticity_checks')
    op.drop_index(op.f('ix_drug_authenticity_checks_expires_at'), table_name='drug_authenticity_checks')
    op.drop_index(op.f('ix_drug_authenticity_checks_drug_name_normalized'), table_name='drug_authenticity_checks')
    op.drop_index(op.f('ix_drug_authenticity_checks_drug_name'), table_name='drug_authenticity_checks')
    op.drop_index(op.f('ix_drug_authenticity_checks_authenticity_status'), table_name='drug_authenticity_checks')
    op.drop_table('drug_authenticity_checks')
    # ### end Alembic commands ###

