"""Add reference models - medical_codes, pharmacy_codes, medical_services

Revision ID: 3246186f7f7c
Revises: 
Create Date: 2025-10-20 20:10:12.977306

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3246186f7f7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('code_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('condition_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('severity_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_codes_code'), 'medical_codes', ['code'], unique=True)
    op.create_index(op.f('ix_medical_codes_condition_name'), 'medical_codes', ['condition_name'], unique=False)
    op.create_table('medical_services',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('service_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('sample_required', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('turnaround_time_days', sa.Integer(), nullable=True),
    sa.Column('requires_fasting', sa.Boolean(), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_services_is_active'), 'medical_services', ['is_active'], unique=False)
    op.create_index(op.f('ix_medical_services_service_name'), 'medical_services', ['service_name'], unique=False)
    op.create_index(op.f('ix_medical_services_service_type'), 'medical_services', ['service_type'], unique=False)
    op.create_table('pharmacy_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('drug_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('drug_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('generic_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('brand_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('dosage_form', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('strength', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('therapeutic_class', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('fda_approved', sa.Boolean(), nullable=False),
    sa.Column('prescription_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_codes_drug_code'), 'pharmacy_codes', ['drug_code'], unique=True)
    op.create_index(op.f('ix_pharmacy_codes_drug_name'), 'pharmacy_codes', ['drug_name'], unique=False)
    op.create_index(op.f('ix_pharmacy_codes_fda_approved'), 'pharmacy_codes', ['fda_approved'], unique=False)
    op.create_index(op.f('ix_pharmacy_codes_generic_name'), 'pharmacy_codes', ['generic_name'], unique=False)
    op.create_index(op.f('ix_pharmacy_codes_therapeutic_class'), 'pharmacy_codes', ['therapeutic_class'], unique=False)
    op.create_table('medical_code_drug_mapping',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medical_code_id', sa.Uuid(), nullable=False),
    sa.Column('pharmacy_code_id', sa.Uuid(), nullable=False),
    sa.Column('effectiveness_rating', sa.Integer(), nullable=True),
    sa.Column('is_first_line_treatment', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medical_code_id'], ['medical_codes.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_code_id'], ['pharmacy_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_code_drug_mapping_medical_code_id'), 'medical_code_drug_mapping', ['medical_code_id'], unique=False)
    op.create_index(op.f('ix_medical_code_drug_mapping_pharmacy_code_id'), 'medical_code_drug_mapping', ['pharmacy_code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_code_drug_mapping_pharmacy_code_id'), table_name='medical_code_drug_mapping')
    op.drop_index(op.f('ix_medical_code_drug_mapping_medical_code_id'), table_name='medical_code_drug_mapping')
    op.drop_table('medical_code_drug_mapping')
    op.drop_index(op.f('ix_pharmacy_codes_therapeutic_class'), table_name='pharmacy_codes')
    op.drop_index(op.f('ix_pharmacy_codes_generic_name'), table_name='pharmacy_codes')
    op.drop_index(op.f('ix_pharmacy_codes_fda_approved'), table_name='pharmacy_codes')
    op.drop_index(op.f('ix_pharmacy_codes_drug_name'), table_name='pharmacy_codes')
    op.drop_index(op.f('ix_pharmacy_codes_drug_code'), table_name='pharmacy_codes')
    op.drop_table('pharmacy_codes')
    op.drop_index(op.f('ix_medical_services_service_type'), table_name='medical_services')
    op.drop_index(op.f('ix_medical_services_service_name'), table_name='medical_services')
    op.drop_index(op.f('ix_medical_services_is_active'), table_name='medical_services')
    op.drop_table('medical_services')
    op.drop_index(op.f('ix_medical_codes_condition_name'), table_name='medical_codes')
    op.drop_index(op.f('ix_medical_codes_code'), table_name='medical_codes')
    op.drop_table('medical_codes')
    # ### end Alembic commands ###

