"""Add insurance models

Revision ID: 3ac8e10fae27
Revises: 78e9c3d61399
Create Date: 2025-10-20 20:25:12.698667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '3ac8e10fae27'
down_revision = '78e9c3d61399'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_companies_company_name'), 'insurance_companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_insurance_companies_license_number'), 'insurance_companies', ['license_number'], unique=True)
    op.create_index(op.f('ix_insurance_companies_user_id'), 'insurance_companies', ['user_id'], unique=True)
    op.create_table('insurance_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('insurance_company_id', sa.Uuid(), nullable=False),
    sa.Column('plan_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('plan_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('coverage_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_premium', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deductible_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('max_coverage_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_company_id'], ['insurance_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plans_insurance_company_id'), 'insurance_plans', ['insurance_company_id'], unique=False)
    op.create_index(op.f('ix_insurance_plans_plan_name'), 'insurance_plans', ['plan_name'], unique=False)
    op.create_index(op.f('ix_insurance_plans_plan_type'), 'insurance_plans', ['plan_type'], unique=False)
    op.create_table('insurance_coverage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('insurance_plan_id', sa.Uuid(), nullable=False),
    sa.Column('coverage_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('coverage_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('max_coverage_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('copay_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('requires_preauth', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_coverage_coverage_type'), 'insurance_coverage', ['coverage_type'], unique=False)
    op.create_index(op.f('ix_insurance_coverage_insurance_plan_id'), 'insurance_coverage', ['insurance_plan_id'], unique=False)
    op.create_index(op.f('ix_insurance_coverage_item_id'), 'insurance_coverage', ['item_id'], unique=False)
    op.create_table('patient_insurance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('insurance_plan_id', sa.Uuid(), nullable=False),
    sa.Column('policy_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('group_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plans.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_insurance_insurance_plan_id'), 'patient_insurance', ['insurance_plan_id'], unique=False)
    op.create_index(op.f('ix_patient_insurance_is_active'), 'patient_insurance', ['is_active'], unique=False)
    op.create_index(op.f('ix_patient_insurance_patient_id'), 'patient_insurance', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_insurance_policy_number'), 'patient_insurance', ['policy_number'], unique=True)
    op.create_table('insurance_claims',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_insurance_id', sa.Uuid(), nullable=False),
    sa.Column('claim_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('claim_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('claimed_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('approved_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_insurance_id'], ['patient_insurance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claims_claim_number'), 'insurance_claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_insurance_claims_claim_type'), 'insurance_claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_insurance_claims_patient_insurance_id'), 'insurance_claims', ['patient_insurance_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_status'), 'insurance_claims', ['status'], unique=False)
    op.create_index(op.f('ix_insurance_claims_submitted_date'), 'insurance_claims', ['submitted_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_claims_submitted_date'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_status'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_patient_insurance_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_claim_type'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_claim_number'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    op.drop_index(op.f('ix_patient_insurance_policy_number'), table_name='patient_insurance')
    op.drop_index(op.f('ix_patient_insurance_patient_id'), table_name='patient_insurance')
    op.drop_index(op.f('ix_patient_insurance_is_active'), table_name='patient_insurance')
    op.drop_index(op.f('ix_patient_insurance_insurance_plan_id'), table_name='patient_insurance')
    op.drop_table('patient_insurance')
    op.drop_index(op.f('ix_insurance_coverage_item_id'), table_name='insurance_coverage')
    op.drop_index(op.f('ix_insurance_coverage_insurance_plan_id'), table_name='insurance_coverage')
    op.drop_index(op.f('ix_insurance_coverage_coverage_type'), table_name='insurance_coverage')
    op.drop_table('insurance_coverage')
    op.drop_index(op.f('ix_insurance_plans_plan_type'), table_name='insurance_plans')
    op.drop_index(op.f('ix_insurance_plans_plan_name'), table_name='insurance_plans')
    op.drop_index(op.f('ix_insurance_plans_insurance_company_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    op.drop_index(op.f('ix_insurance_companies_user_id'), table_name='insurance_companies')
    op.drop_index(op.f('ix_insurance_companies_license_number'), table_name='insurance_companies')
    op.drop_index(op.f('ix_insurance_companies_company_name'), table_name='insurance_companies')
    op.drop_table('insurance_companies')
    # ### end Alembic commands ###

