"""Add hospital operations and bed admission_id column

Revision ID: d06a6d3a1fde
Revises: ee0517d7a9dc
Create Date: 2025-10-20 20:28:34.568367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'd06a6d3a1fde'
down_revision = 'ee0517d7a9dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=True),
    sa.Column('bed_occupancy_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('average_length_of_stay', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('emergency_wait_time_avg', sa.Integer(), nullable=True),
    sa.Column('patient_satisfaction_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('readmission_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('infection_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('mortality_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('staff_to_patient_ratio', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('revenue', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('operating_expenses', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_metrics_hospital_id'), 'hospital_metrics', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_metrics_metric_date'), 'hospital_metrics', ['metric_date'], unique=False)
    op.create_table('hospital_lab_tests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('ordering_doctor_id', sa.Uuid(), nullable=False),
    sa.Column('test_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('test_category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('specimen_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('collection_datetime', sa.DateTime(), nullable=True),
    sa.Column('result_datetime', sa.DateTime(), nullable=True),
    sa.Column('test_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normal_range', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('technician_notes', sa.Text(), nullable=True),
    sa.Column('doctor_interpretation', sa.Text(), nullable=True),
    sa.Column('report_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['ordering_doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_lab_tests_collection_datetime'), 'hospital_lab_tests', ['collection_datetime'], unique=False)
    op.create_index(op.f('ix_hospital_lab_tests_hospital_id'), 'hospital_lab_tests', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_lab_tests_ordering_doctor_id'), 'hospital_lab_tests', ['ordering_doctor_id'], unique=False)
    op.create_index(op.f('ix_hospital_lab_tests_patient_id'), 'hospital_lab_tests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_hospital_lab_tests_test_category'), 'hospital_lab_tests', ['test_category'], unique=False)
    op.create_index(op.f('ix_hospital_lab_tests_test_status'), 'hospital_lab_tests', ['test_status'], unique=False)
    op.create_table('hospital_admissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('admitting_doctor_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('admission_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('admission_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('admission_datetime', sa.DateTime(), nullable=False),
    sa.Column('discharge_datetime', sa.DateTime(), nullable=True),
    sa.Column('estimated_discharge_date', sa.Date(), nullable=True),
    sa.Column('admission_reason', sa.Text(), nullable=True),
    sa.Column('admission_diagnosis', sa.Text(), nullable=True),
    sa.Column('discharge_diagnosis', sa.Text(), nullable=True),
    sa.Column('discharge_summary', sa.Text(), nullable=True),
    sa.Column('discharge_instructions', sa.Text(), nullable=True),
    sa.Column('admission_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('discharge_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('insurance_coverage_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admitting_doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['hospital_departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_admissions_admission_datetime'), 'hospital_admissions', ['admission_datetime'], unique=False)
    op.create_index(op.f('ix_hospital_admissions_admission_number'), 'hospital_admissions', ['admission_number'], unique=True)
    op.create_index(op.f('ix_hospital_admissions_admission_status'), 'hospital_admissions', ['admission_status'], unique=False)
    op.create_index(op.f('ix_hospital_admissions_admitting_doctor_id'), 'hospital_admissions', ['admitting_doctor_id'], unique=False)
    op.create_index(op.f('ix_hospital_admissions_department_id'), 'hospital_admissions', ['department_id'], unique=False)
    op.create_index(op.f('ix_hospital_admissions_hospital_id'), 'hospital_admissions', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_admissions_patient_id'), 'hospital_admissions', ['patient_id'], unique=False)
    op.create_table('staff_schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('staff_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=True),
    sa.Column('shift_start_time', sa.Time(), nullable=True),
    sa.Column('shift_end_time', sa.Time(), nullable=True),
    sa.Column('shift_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=False),
    sa.Column('actual_clock_in', sa.DateTime(), nullable=True),
    sa.Column('actual_clock_out', sa.DateTime(), nullable=True),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hospital_departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_schedules_department_id'), 'staff_schedules', ['department_id'], unique=False)
    op.create_index(op.f('ix_staff_schedules_hospital_id'), 'staff_schedules', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_staff_schedules_shift_date'), 'staff_schedules', ['shift_date'], unique=False)
    op.create_index(op.f('ix_staff_schedules_staff_id'), 'staff_schedules', ['staff_id'], unique=False)
    op.create_table('emergency_visits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(), nullable=True),
    sa.Column('triage_level', sa.Integer(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('vital_signs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attending_doctor_id', sa.Uuid(), nullable=True),
    sa.Column('triage_nurse_id', sa.Uuid(), nullable=True),
    sa.Column('visit_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('disposition', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('wait_time_minutes', sa.Integer(), nullable=True),
    sa.Column('treatment_time_minutes', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attending_doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['triage_nurse_id'], ['hospital_staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_visits_arrival_datetime'), 'emergency_visits', ['arrival_datetime'], unique=False)
    op.create_index(op.f('ix_emergency_visits_attending_doctor_id'), 'emergency_visits', ['attending_doctor_id'], unique=False)
    op.create_index(op.f('ix_emergency_visits_hospital_id'), 'emergency_visits', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_emergency_visits_patient_id'), 'emergency_visits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_emergency_visits_triage_level'), 'emergency_visits', ['triage_level'], unique=False)
    op.create_index(op.f('ix_emergency_visits_visit_status'), 'emergency_visits', ['visit_status'], unique=False)
    op.create_table('hospital_bills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('admission_id', sa.Uuid(), nullable=True),
    sa.Column('bill_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('bill_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('outstanding_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('insurance_claim_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['hospital_admissions.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['insurance_claim_id'], ['insurance_claims.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_bills_admission_id'), 'hospital_bills', ['admission_id'], unique=False)
    op.create_index(op.f('ix_hospital_bills_bill_date'), 'hospital_bills', ['bill_date'], unique=False)
    op.create_index(op.f('ix_hospital_bills_bill_number'), 'hospital_bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_hospital_bills_due_date'), 'hospital_bills', ['due_date'], unique=False)
    op.create_index(op.f('ix_hospital_bills_hospital_id'), 'hospital_bills', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_bills_patient_id'), 'hospital_bills', ['patient_id'], unique=False)
    op.create_index(op.f('ix_hospital_bills_payment_status'), 'hospital_bills', ['payment_status'], unique=False)
    op.create_table('surgeries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('primary_surgeon_id', sa.Uuid(), nullable=False),
    sa.Column('anesthesiologist_id', sa.Uuid(), nullable=True),
    sa.Column('surgery_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('procedure_codes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('scheduled_datetime', sa.DateTime(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('operating_room_id', sa.Uuid(), nullable=True),
    sa.Column('surgery_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('pre_op_notes', sa.Text(), nullable=True),
    sa.Column('surgical_notes', sa.Text(), nullable=True),
    sa.Column('post_op_notes', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('actual_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anesthesiologist_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['operating_room_id'], ['hospital_rooms.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['primary_surgeon_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surgeries_hospital_id'), 'surgeries', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_surgeries_operating_room_id'), 'surgeries', ['operating_room_id'], unique=False)
    op.create_index(op.f('ix_surgeries_patient_id'), 'surgeries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_surgeries_primary_surgeon_id'), 'surgeries', ['primary_surgeon_id'], unique=False)
    op.create_index(op.f('ix_surgeries_scheduled_datetime'), 'surgeries', ['scheduled_datetime'], unique=False)
    op.create_index(op.f('ix_surgeries_surgery_status'), 'surgeries', ['surgery_status'], unique=False)
    op.create_table('hospital_bill_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hospital_bill_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('item_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_bill_id'], ['hospital_bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_bill_items_hospital_bill_id'), 'hospital_bill_items', ['hospital_bill_id'], unique=False)
    op.create_index(op.f('ix_hospital_bill_items_item_type'), 'hospital_bill_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_hospital_bill_items_provider_id'), 'hospital_bill_items', ['provider_id'], unique=False)
    op.create_index(op.f('ix_hospital_bill_items_service_date'), 'hospital_bill_items', ['service_date'], unique=False)
    op.create_table('surgery_team',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('surgery_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('staff_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgeries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surgery_team_staff_id'), 'surgery_team', ['staff_id'], unique=False)
    op.create_index(op.f('ix_surgery_team_surgery_id'), 'surgery_team', ['surgery_id'], unique=False)
    op.add_column('hospital_beds', sa.Column('admission_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_hospital_beds_admission_id'), 'hospital_beds', ['admission_id'], unique=False)
    op.create_foreign_key(None, 'hospital_beds', 'hospital_admissions', ['admission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospital_beds', type_='foreignkey')
    op.drop_index(op.f('ix_hospital_beds_admission_id'), table_name='hospital_beds')
    op.drop_column('hospital_beds', 'admission_id')
    op.drop_index(op.f('ix_surgery_team_surgery_id'), table_name='surgery_team')
    op.drop_index(op.f('ix_surgery_team_staff_id'), table_name='surgery_team')
    op.drop_table('surgery_team')
    op.drop_index(op.f('ix_hospital_bill_items_service_date'), table_name='hospital_bill_items')
    op.drop_index(op.f('ix_hospital_bill_items_provider_id'), table_name='hospital_bill_items')
    op.drop_index(op.f('ix_hospital_bill_items_item_type'), table_name='hospital_bill_items')
    op.drop_index(op.f('ix_hospital_bill_items_hospital_bill_id'), table_name='hospital_bill_items')
    op.drop_table('hospital_bill_items')
    op.drop_index(op.f('ix_surgeries_surgery_status'), table_name='surgeries')
    op.drop_index(op.f('ix_surgeries_scheduled_datetime'), table_name='surgeries')
    op.drop_index(op.f('ix_surgeries_primary_surgeon_id'), table_name='surgeries')
    op.drop_index(op.f('ix_surgeries_patient_id'), table_name='surgeries')
    op.drop_index(op.f('ix_surgeries_operating_room_id'), table_name='surgeries')
    op.drop_index(op.f('ix_surgeries_hospital_id'), table_name='surgeries')
    op.drop_table('surgeries')
    op.drop_index(op.f('ix_hospital_bills_payment_status'), table_name='hospital_bills')
    op.drop_index(op.f('ix_hospital_bills_patient_id'), table_name='hospital_bills')
    op.drop_index(op.f('ix_hospital_bills_hospital_id'), table_name='hospital_bills')
    op.drop_index(op.f('ix_hospital_bills_due_date'), table_name='hospital_bills')
    op.drop_index(op.f('ix_hospital_bills_bill_number'), table_name='hospital_bills')
    op.drop_index(op.f('ix_hospital_bills_bill_date'), table_name='hospital_bills')
    op.drop_index(op.f('ix_hospital_bills_admission_id'), table_name='hospital_bills')
    op.drop_table('hospital_bills')
    op.drop_index(op.f('ix_emergency_visits_visit_status'), table_name='emergency_visits')
    op.drop_index(op.f('ix_emergency_visits_triage_level'), table_name='emergency_visits')
    op.drop_index(op.f('ix_emergency_visits_patient_id'), table_name='emergency_visits')
    op.drop_index(op.f('ix_emergency_visits_hospital_id'), table_name='emergency_visits')
    op.drop_index(op.f('ix_emergency_visits_attending_doctor_id'), table_name='emergency_visits')
    op.drop_index(op.f('ix_emergency_visits_arrival_datetime'), table_name='emergency_visits')
    op.drop_table('emergency_visits')
    op.drop_index(op.f('ix_staff_schedules_staff_id'), table_name='staff_schedules')
    op.drop_index(op.f('ix_staff_schedules_shift_date'), table_name='staff_schedules')
    op.drop_index(op.f('ix_staff_schedules_hospital_id'), table_name='staff_schedules')
    op.drop_index(op.f('ix_staff_schedules_department_id'), table_name='staff_schedules')
    op.drop_table('staff_schedules')
    op.drop_index(op.f('ix_hospital_admissions_patient_id'), table_name='hospital_admissions')
    op.drop_index(op.f('ix_hospital_admissions_hospital_id'), table_name='hospital_admissions')
    op.drop_index(op.f('ix_hospital_admissions_department_id'), table_name='hospital_admissions')
    op.drop_index(op.f('ix_hospital_admissions_admitting_doctor_id'), table_name='hospital_admissions')
    op.drop_index(op.f('ix_hospital_admissions_admission_status'), table_name='hospital_admissions')
    op.drop_index(op.f('ix_hospital_admissions_admission_number'), table_name='hospital_admissions')
    op.drop_index(op.f('ix_hospital_admissions_admission_datetime'), table_name='hospital_admissions')
    op.drop_table('hospital_admissions')
    op.drop_index(op.f('ix_hospital_lab_tests_test_status'), table_name='hospital_lab_tests')
    op.drop_index(op.f('ix_hospital_lab_tests_test_category'), table_name='hospital_lab_tests')
    op.drop_index(op.f('ix_hospital_lab_tests_patient_id'), table_name='hospital_lab_tests')
    op.drop_index(op.f('ix_hospital_lab_tests_ordering_doctor_id'), table_name='hospital_lab_tests')
    op.drop_index(op.f('ix_hospital_lab_tests_hospital_id'), table_name='hospital_lab_tests')
    op.drop_index(op.f('ix_hospital_lab_tests_collection_datetime'), table_name='hospital_lab_tests')
    op.drop_table('hospital_lab_tests')
    op.drop_index(op.f('ix_hospital_metrics_metric_date'), table_name='hospital_metrics')
    op.drop_index(op.f('ix_hospital_metrics_hospital_id'), table_name='hospital_metrics')
    op.drop_table('hospital_metrics')
    # ### end Alembic commands ###

