"""Initial migration - health sessions and messages

Revision ID: de010a227061
Revises: 
Create Date: 2025-10-14 11:51:14.475911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de010a227061'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('session_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_sessions_is_active'), 'health_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_health_sessions_user_id'), 'health_sessions', ['user_id'], unique=False)
    op.create_table('health_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['health_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_messages_session_id'), 'health_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_messages_session_id'), table_name='health_messages')
    op.drop_table('health_messages')
    op.drop_index(op.f('ix_health_sessions_user_id'), table_name='health_sessions')
    op.drop_index(op.f('ix_health_sessions_is_active'), table_name='health_sessions')
    op.drop_table('health_sessions')
    # ### end Alembic commands ###

