"""Add hospital models and doctor hospital_id column

Revision ID: ee0517d7a9dc
Revises: 3ac8e10fae27
Create Date: 2025-10-20 20:27:10.635761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'ee0517d7a9dc'
down_revision = '3ac8e10fae27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hospital_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('services_offered', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('accreditation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_hospital_type'), 'hospitals', ['hospital_type'], unique=False)
    op.create_index(op.f('ix_hospitals_license_number'), 'hospitals', ['license_number'], unique=True)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_index(op.f('ix_hospitals_user_id'), 'hospitals', ['user_id'], unique=True)
    op.create_table('hospital_departments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('department_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('head_doctor_id', sa.Uuid(), nullable=True),
    sa.Column('bed_capacity', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('specialized_equipment', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['head_doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_departments_department_type'), 'hospital_departments', ['department_type'], unique=False)
    op.create_index(op.f('ix_hospital_departments_head_doctor_id'), 'hospital_departments', ['head_doctor_id'], unique=False)
    op.create_index(op.f('ix_hospital_departments_hospital_id'), 'hospital_departments', ['hospital_id'], unique=False)
    op.create_table('hospital_beds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('bed_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('bed_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('room_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('floor_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('bed_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('daily_rate', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_cleaned', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hospital_departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_beds_bed_status'), 'hospital_beds', ['bed_status'], unique=False)
    op.create_index(op.f('ix_hospital_beds_department_id'), 'hospital_beds', ['department_id'], unique=False)
    op.create_index(op.f('ix_hospital_beds_hospital_id'), 'hospital_beds', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_beds_patient_id'), 'hospital_beds', ['patient_id'], unique=False)
    op.create_table('hospital_equipment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('equipment_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('equipment_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('model_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('equipment_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cost_per_use', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('maintenance_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_portable', sa.Boolean(), nullable=False),
    sa.Column('requires_specialist', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hospital_departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_equipment_department_id'), 'hospital_equipment', ['department_id'], unique=False)
    op.create_index(op.f('ix_hospital_equipment_equipment_status'), 'hospital_equipment', ['equipment_status'], unique=False)
    op.create_index(op.f('ix_hospital_equipment_equipment_type'), 'hospital_equipment', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_hospital_equipment_hospital_id'), 'hospital_equipment', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_equipment_next_maintenance_date'), 'hospital_equipment', ['next_maintenance_date'], unique=False)
    op.create_index(op.f('ix_hospital_equipment_serial_number'), 'hospital_equipment', ['serial_number'], unique=True)
    op.create_table('hospital_inventory',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('item_category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('unit_of_measure', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('minimum_stock_level', sa.Integer(), nullable=False),
    sa.Column('maximum_stock_level', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('storage_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_restocked_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hospital_departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_inventory_current_stock'), 'hospital_inventory', ['current_stock'], unique=False)
    op.create_index(op.f('ix_hospital_inventory_department_id'), 'hospital_inventory', ['department_id'], unique=False)
    op.create_index(op.f('ix_hospital_inventory_expiry_date'), 'hospital_inventory', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_hospital_inventory_hospital_id'), 'hospital_inventory', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_inventory_item_category'), 'hospital_inventory', ['item_category'], unique=False)
    op.create_index(op.f('ix_hospital_inventory_item_code'), 'hospital_inventory', ['item_code'], unique=True)
    op.create_table('hospital_rooms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('room_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('room_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('floor_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=False),
    sa.Column('room_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('daily_rate', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('amenities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('equipment_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('accessibility_features', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hospital_departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_rooms_department_id'), 'hospital_rooms', ['department_id'], unique=False)
    op.create_index(op.f('ix_hospital_rooms_hospital_id'), 'hospital_rooms', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_rooms_room_status'), 'hospital_rooms', ['room_status'], unique=False)
    op.create_index(op.f('ix_hospital_rooms_room_type'), 'hospital_rooms', ['room_type'], unique=False)
    op.create_table('hospital_staff',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('staff_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('position_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qualifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('shift_pattern', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('hourly_rate', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('emergency_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hospital_departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_staff_department_id'), 'hospital_staff', ['department_id'], unique=False)
    op.create_index(op.f('ix_hospital_staff_employment_status'), 'hospital_staff', ['employment_status'], unique=False)
    op.create_index(op.f('ix_hospital_staff_hospital_id'), 'hospital_staff', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_staff_staff_type'), 'hospital_staff', ['staff_type'], unique=False)
    op.create_index(op.f('ix_hospital_staff_user_id'), 'hospital_staff', ['user_id'], unique=True)
    op.add_column('doctors', sa.Column('hospital_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False)
    op.create_foreign_key(None, 'doctors', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_doctors_hospital_id'), table_name='doctors')
    op.drop_column('doctors', 'hospital_id')
    op.drop_index(op.f('ix_hospital_staff_user_id'), table_name='hospital_staff')
    op.drop_index(op.f('ix_hospital_staff_staff_type'), table_name='hospital_staff')
    op.drop_index(op.f('ix_hospital_staff_hospital_id'), table_name='hospital_staff')
    op.drop_index(op.f('ix_hospital_staff_employment_status'), table_name='hospital_staff')
    op.drop_index(op.f('ix_hospital_staff_department_id'), table_name='hospital_staff')
    op.drop_table('hospital_staff')
    op.drop_index(op.f('ix_hospital_rooms_room_type'), table_name='hospital_rooms')
    op.drop_index(op.f('ix_hospital_rooms_room_status'), table_name='hospital_rooms')
    op.drop_index(op.f('ix_hospital_rooms_hospital_id'), table_name='hospital_rooms')
    op.drop_index(op.f('ix_hospital_rooms_department_id'), table_name='hospital_rooms')
    op.drop_table('hospital_rooms')
    op.drop_index(op.f('ix_hospital_inventory_item_code'), table_name='hospital_inventory')
    op.drop_index(op.f('ix_hospital_inventory_item_category'), table_name='hospital_inventory')
    op.drop_index(op.f('ix_hospital_inventory_hospital_id'), table_name='hospital_inventory')
    op.drop_index(op.f('ix_hospital_inventory_expiry_date'), table_name='hospital_inventory')
    op.drop_index(op.f('ix_hospital_inventory_department_id'), table_name='hospital_inventory')
    op.drop_index(op.f('ix_hospital_inventory_current_stock'), table_name='hospital_inventory')
    op.drop_table('hospital_inventory')
    op.drop_index(op.f('ix_hospital_equipment_serial_number'), table_name='hospital_equipment')
    op.drop_index(op.f('ix_hospital_equipment_next_maintenance_date'), table_name='hospital_equipment')
    op.drop_index(op.f('ix_hospital_equipment_hospital_id'), table_name='hospital_equipment')
    op.drop_index(op.f('ix_hospital_equipment_equipment_type'), table_name='hospital_equipment')
    op.drop_index(op.f('ix_hospital_equipment_equipment_status'), table_name='hospital_equipment')
    op.drop_index(op.f('ix_hospital_equipment_department_id'), table_name='hospital_equipment')
    op.drop_table('hospital_equipment')
    op.drop_index(op.f('ix_hospital_beds_patient_id'), table_name='hospital_beds')
    op.drop_index(op.f('ix_hospital_beds_hospital_id'), table_name='hospital_beds')
    op.drop_index(op.f('ix_hospital_beds_department_id'), table_name='hospital_beds')
    op.drop_index(op.f('ix_hospital_beds_bed_status'), table_name='hospital_beds')
    op.drop_table('hospital_beds')
    op.drop_index(op.f('ix_hospital_departments_hospital_id'), table_name='hospital_departments')
    op.drop_index(op.f('ix_hospital_departments_head_doctor_id'), table_name='hospital_departments')
    op.drop_index(op.f('ix_hospital_departments_department_type'), table_name='hospital_departments')
    op.drop_table('hospital_departments')
    op.drop_index(op.f('ix_hospitals_user_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_license_number'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_hospital_type'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###

